/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
    }
    interface NpColorSample {
        /**
          * Base color for the sphere
         */
        "color": string;
    }
    interface TaskManager {
    }
    interface TemplateTest {
        "arr": any;
    }
    interface ThreeComponent {
    }
    interface ToolTip {
        "text": any;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLNpColorSampleElement extends Components.NpColorSample, HTMLStencilElement {
    }
    var HTMLNpColorSampleElement: {
        prototype: HTMLNpColorSampleElement;
        new (): HTMLNpColorSampleElement;
    };
    interface HTMLTaskManagerElement extends Components.TaskManager, HTMLStencilElement {
    }
    var HTMLTaskManagerElement: {
        prototype: HTMLTaskManagerElement;
        new (): HTMLTaskManagerElement;
    };
    interface HTMLTemplateTestElement extends Components.TemplateTest, HTMLStencilElement {
    }
    var HTMLTemplateTestElement: {
        prototype: HTMLTemplateTestElement;
        new (): HTMLTemplateTestElement;
    };
    interface HTMLThreeComponentElement extends Components.ThreeComponent, HTMLStencilElement {
    }
    var HTMLThreeComponentElement: {
        prototype: HTMLThreeComponentElement;
        new (): HTMLThreeComponentElement;
    };
    interface HTMLToolTipElement extends Components.ToolTip, HTMLStencilElement {
    }
    var HTMLToolTipElement: {
        prototype: HTMLToolTipElement;
        new (): HTMLToolTipElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "np-color-sample": HTMLNpColorSampleElement;
        "task-manager": HTMLTaskManagerElement;
        "template-test": HTMLTemplateTestElement;
        "three-component": HTMLThreeComponentElement;
        "tool-tip": HTMLToolTipElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
    }
    interface NpColorSample {
        /**
          * Base color for the sphere
         */
        "color"?: string;
    }
    interface TaskManager {
    }
    interface TemplateTest {
        "arr"?: any;
    }
    interface ThreeComponent {
    }
    interface ToolTip {
        "text"?: any;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "np-color-sample": NpColorSample;
        "task-manager": TaskManager;
        "template-test": TemplateTest;
        "three-component": ThreeComponent;
        "tool-tip": ToolTip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "np-color-sample": LocalJSX.NpColorSample & JSXBase.HTMLAttributes<HTMLNpColorSampleElement>;
            "task-manager": LocalJSX.TaskManager & JSXBase.HTMLAttributes<HTMLTaskManagerElement>;
            "template-test": LocalJSX.TemplateTest & JSXBase.HTMLAttributes<HTMLTemplateTestElement>;
            "three-component": LocalJSX.ThreeComponent & JSXBase.HTMLAttributes<HTMLThreeComponentElement>;
            "tool-tip": LocalJSX.ToolTip & JSXBase.HTMLAttributes<HTMLToolTipElement>;
        }
    }
}
