/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Color } from "./components/story-test/color.enum";
export { Color } from "./components/story-test/color.enum";
export namespace Components {
    interface ComponentsTest {
    }
    interface FluidLevel {
    }
    interface NpSlider {
        "ariaLabelledBy": string;
        "disabled": boolean;
        "max": number;
        "min": number;
        "orientation": string;
        "range": boolean;
        "sliderStyle": any;
        "step": number;
        "styleClass": string;
        "tabindex": number;
        "value": number | number[];
    }
    interface StoryTest {
        /**
          * Color of the component
          * @name Color
          * @type {Color}
          * @default Red
         */
        "color": Color;
        /**
          * Text to display
          * @name Text
          * @type {string}
         */
        "text": string;
    }
}
export interface NpSliderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNpSliderElement;
}
export interface StoryTestCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStoryTestElement;
}
declare global {
    interface HTMLComponentsTestElement extends Components.ComponentsTest, HTMLStencilElement {
    }
    var HTMLComponentsTestElement: {
        prototype: HTMLComponentsTestElement;
        new (): HTMLComponentsTestElement;
    };
    interface HTMLFluidLevelElement extends Components.FluidLevel, HTMLStencilElement {
    }
    var HTMLFluidLevelElement: {
        prototype: HTMLFluidLevelElement;
        new (): HTMLFluidLevelElement;
    };
    interface HTMLNpSliderElementEventMap {
        "changeEvent": any;
        "slideEndEvent": any;
    }
    interface HTMLNpSliderElement extends Components.NpSlider, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNpSliderElementEventMap>(type: K, listener: (this: HTMLNpSliderElement, ev: NpSliderCustomEvent<HTMLNpSliderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNpSliderElementEventMap>(type: K, listener: (this: HTMLNpSliderElement, ev: NpSliderCustomEvent<HTMLNpSliderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNpSliderElement: {
        prototype: HTMLNpSliderElement;
        new (): HTMLNpSliderElement;
    };
    interface HTMLStoryTestElementEventMap {
        "clickEventBy": any;
    }
    interface HTMLStoryTestElement extends Components.StoryTest, HTMLStencilElement {
        addEventListener<K extends keyof HTMLStoryTestElementEventMap>(type: K, listener: (this: HTMLStoryTestElement, ev: StoryTestCustomEvent<HTMLStoryTestElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLStoryTestElementEventMap>(type: K, listener: (this: HTMLStoryTestElement, ev: StoryTestCustomEvent<HTMLStoryTestElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLStoryTestElement: {
        prototype: HTMLStoryTestElement;
        new (): HTMLStoryTestElement;
    };
    interface HTMLElementTagNameMap {
        "components-test": HTMLComponentsTestElement;
        "fluid-level": HTMLFluidLevelElement;
        "np-slider": HTMLNpSliderElement;
        "story-test": HTMLStoryTestElement;
    }
}
declare namespace LocalJSX {
    interface ComponentsTest {
    }
    interface FluidLevel {
    }
    interface NpSlider {
        "ariaLabelledBy"?: string;
        "disabled"?: boolean;
        "max"?: number;
        "min"?: number;
        "onChangeEvent"?: (event: NpSliderCustomEvent<any>) => void;
        "onSlideEndEvent"?: (event: NpSliderCustomEvent<any>) => void;
        "orientation"?: string;
        "range"?: boolean;
        "sliderStyle"?: any;
        "step"?: number;
        "styleClass"?: string;
        "tabindex"?: number;
        "value"?: number | number[];
    }
    interface StoryTest {
        /**
          * Color of the component
          * @name Color
          * @type {Color}
          * @default Red
         */
        "color"?: Color;
        /**
          * Event emitted by the component when clicked
         */
        "onClickEventBy"?: (event: StoryTestCustomEvent<any>) => void;
        /**
          * Text to display
          * @name Text
          * @type {string}
         */
        "text"?: string;
    }
    interface IntrinsicElements {
        "components-test": ComponentsTest;
        "fluid-level": FluidLevel;
        "np-slider": NpSlider;
        "story-test": StoryTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "components-test": LocalJSX.ComponentsTest & JSXBase.HTMLAttributes<HTMLComponentsTestElement>;
            "fluid-level": LocalJSX.FluidLevel & JSXBase.HTMLAttributes<HTMLFluidLevelElement>;
            "np-slider": LocalJSX.NpSlider & JSXBase.HTMLAttributes<HTMLNpSliderElement>;
            "story-test": LocalJSX.StoryTest & JSXBase.HTMLAttributes<HTMLStoryTestElement>;
        }
    }
}
