/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FluidLevel {
    }
}
declare global {
    interface HTMLFluidLevelElement extends Components.FluidLevel, HTMLStencilElement {
    }
    var HTMLFluidLevelElement: {
        prototype: HTMLFluidLevelElement;
        new (): HTMLFluidLevelElement;
    };
    interface HTMLElementTagNameMap {
        "fluid-level": HTMLFluidLevelElement;
    }
}
declare namespace LocalJSX {
    interface FluidLevel {
    }
    interface IntrinsicElements {
        "fluid-level": FluidLevel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fluid-level": LocalJSX.FluidLevel & JSXBase.HTMLAttributes<HTMLFluidLevelElement>;
        }
    }
}
